version: '3'
services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: 'mongodb'
    env_file: ./containerConfig/mongodb.env
    ports:
      - 27017:27017
    volumes:
      - ./containerConfig/initMongo.js:/docker-entrypoint-initdb.d/initMongo.js
      - ./data/mongdb:/data/db
    command: mongod --logpath=/dev/null # --quiet
volumes:
  mongodb_data: